### ISSUE TITLE
Fails to load if package is recently published

### ISSUE THREAD

**Issue by ItsNickBarry** [antoniormrzz/npm-stats#1]
The site appears to fail to load if the queried user's account contains a recently published package.  NPM takes some time before download statistics appear on their website; the same probably applies to their API, causing an error.

**Comment by antoniormrzz** [comment]
Hey, thanks for the heads up, I'm aware of this, unfortunately, the npm package is listed for user but can't be found on the backend. I just need to ignore that package I guess.
I'm sorry for the inconvenience, will fix this when I have time. Feel free to do a PR if you can. Thanks.

**Comment by antoniormrzz** [comment]
@ItsNickBarry The issue has been fixed. https://www.npmstats.info/ 
Proud of my speedy development :D

**Comment by antoniormrzz** [comment]
Thank you for visiting the website. There was another problem with the homepage button on some of your packages, which I became aware of thanks to the logs. It's been since fixed so they can be visited.

**Comment by ItsNickBarry** [comment]
Good project, I like the new design.
